# Generated by Django 4.0.2 on 2022-02-09 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_author_book_info_book_market_price_book_pub_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
    ]
