# Generated by Django 4.0.2 on 2022-02-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_book_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '图书'},
        ),
    ]
