# Generated by Django 4.0.2 on 2022-02-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '图书', 'verbose_name_plural': '图书'},
        ),
    ]
